### PR TITLE
fix(cache): use `process.geteuid()` for virtual users

### PR DESCRIPTION
**Pull request by ST-DDT**
Fixes https://github.com/esbuild-kit/tsx/issues/352

- https://github.com/esbuild-kit/tsx/issues/352
- https://github.com/esbuild-kit/tsx/pull/332

Restored after #355 has been closed by accident.

- #355

### CODE REVIEW

**Comment by privatenumber** [comment]
Thank you!

**Comment by privatenumber** [comment]
:tada: This issue has been resolved in v4.1.0

If you appreciate this project, please consider [supporting this project by sponsoring](https://github.com/sponsors/privatenumber) :heart: :pray:

**Comment by ST-DDT** [comment]
@privatenumber Is it possible to get this fix backported to v3?

**Comment by privatenumber** [comment]
Since this is extra work I won't be benefitting from, happy to do it for a fee. Feel free to DM on Twitter if you're interested.

**Pull request merged**
