### PR TITLE
fix(esm): resolve absolute paths

### PR DESCRIPTION
**Pull request by fardjad**
This PR attempts to fix the issue described here: https://github.com/privatenumber/tsx/issues/543

### CODE REVIEW

**Comment by privatenumber** [comment]
@fardjad Would you mind adding a test?

**Comment by fardjad** [comment]
@privatenumber I wasn't sure where would be the best place to add the test. I updated my PR. Do you think the approach and the place for adding the test make sense or do you have something else in mind?

**Comment by fardjad** [comment]
@privatenumber Of course! I updated my PR.

I wasn't sure where the best place to add the test would be. I decided to put it under `register / unregister` group as it affects the resolver (and not `tsImport` itself). Do you think the approach and the location for adding the test make sense, or do you have something else in mind?

**Comment by privatenumber** [comment]
That works, but I consolidated it into the smoke test—previously, our tests would take super long from spawning so many processes.

Thanks for your contribution!

**Comment by privatenumber** [comment]
:tada: This issue has been resolved in v4.9.2

If you appreciate this project, please consider [supporting this project by sponsoring](https://github.com/sponsors/privatenumber) :heart: :pray:

**Pull request merged**
