### PR TITLE
ci(lock-threads): fix yaml syntax

### PR DESCRIPTION
**Pull request by jbergstroem**
The current syntax for the lock threads job is incorrect. This PR addresses it.

Also, add actionlint to check job syntax as part of the PR workflow.
Finally, format syntax as suggested by actionlint.

Refs: https://github.com/privatenumber/tsx/pull/441

### CODE REVIEW

**Comment by privatenumber** [comment]
Was there anything actually broken that this fixes?

**Comment by jbergstroem** [comment]
> Was there anything actually broken that this fixes?

yes, the thread job is broken: https://github.com/privatenumber/tsx/actions/workflows/lock-threads.yml

**Comment by privatenumber** [comment]
Gotcha! It looks like I accidentally broke it by removing the `-` in the last commit, after confirming it to work: https://github.com/privatenumber/tsx/pull/441/files

I appreciate the pull request, but I'm thinking adding another workflow just to check my workflows might be a bit much since it spawns a whole OS just to validate YAML files. Would you mind removing the `actionlint` part and any changes that aren't related to fixing the issue?

I'll look into linting YAML files using ESLint.

**Comment by jbergstroem** [comment]
> Gotcha! It looks like I accidentally broke it by removing the `-` in the last commit, after confirming it to work: [#441 (files)](https://github.com/privatenumber/tsx/pull/441/files)
> 
> I appreciate the pull request, but I'm thinking adding another workflow just to check my workflows might be a bit much since it spawns a whole OS just to validate YAML files. Would you mind removing the `actionlint` part and any changes that aren't related to fixing the issue?
> 
> I'll look into linting YAML files using ESLint.

All good; reverted to minimal changes.

**Comment by privatenumber** [comment]
:tada: This issue has been resolved in v4.7.0

If you appreciate this project, please consider [supporting this project by sponsoring](https://github.com/sponsors/privatenumber) :heart: :pray:

**Pull request merged**
