### PR TITLE
fix: respect the same ignore setting passed to chokidar

### LINKED ISSUE #221: TSX is not ignoring node_modules or respecting --ignore flags
### Bug description

I discovered this while working in a monorepo. I am using TSX to watch my application project. I was making edits to one of my local dependencies and my application was restarting. As I started to investigate I noticed that:

- TSX is not ignoring node_modules
- TSX does not seem to respect `--ignore` flags
- TSX is watching files located outside of the `cwd`

All of the above behaviors seem unexpected, especially the last one. Here's a repro:

### Reproduction

https://github.com/DesignByOnyx/tsx-restart-ignore-bug

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 11.03 GB / 15.48 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    npm: 9.6.4 - ~/.nvm/versions/node/v16.19.0/bin/npm
  npmPackages:
    tsx: ^3.12.6 => 3.12.6
```

### Can you work on a fix?

- [X] I’m interested in opening a pull request to address this issue.

### PR DESCRIPTION
**Pull request by DesignByOnyx**
This fixes #221.

### CODE REVIEW

**Comment by DesignByOnyx** [comment]
Regarding the failing test - I am not able to reproduce on my machine (Ubuntu 20). `pnpm test` passes without issue. I hate to be the "works on my machine" guy, but I'm not sure how to proceed.

The `micromatch` library supports node [`>=8.6`](https://github.com/micromatch/micromatch/blob/master/package.json#L34) and is written in CJS, so I don't think any of my changes really affect the one failing test:

image

**Comment by privatenumber** [comment]
No worries, it's a flaky test.

Will look at this more closely later, thanks for the PR.

**Comment by privatenumber** [comment]
Switching to `anymatch` as that's what chokidar uses.

**Comment by privatenumber** [comment]
I'm not sure if this actually fixes the problem you're describing in the issue.

I'm skeptical if chokidar will watch a file that is configured to be ignored even if it's passed in.

**Comment by DesignByOnyx** [comment]
Please see my reply on the linked issue: https://github.com/esbuild-kit/tsx/issues/221#issuecomment-1732034537

**Pull request closed without merging**
